language: node_js
node_js:
- '12'
notifications:
  slack:
    secure: m5+Xgw+I2r3fAtFVYw+HZ12CzAGHNKHIgLFb6vVWpNCi2jpVaU/FCgX6mSmVuV3cNGplt6tKg/AbggCv/QOdLv+2hoSI0qilZ0ffsxLlGLQ4kvw6gX2ugYqC75rXRzZQsd/EsK7j+cFKl6e7GTgZC6YFVU+MsIPfM9Hkpdn/KNenDPDX/RTaLZROvlO5Z71YR3/vXdXK4K7s76lH6r8WJes35hV545j0mo0uNEx0m5jvyK/VZNiGDPgJH83QHRqThCderIyRvewrscMTriCUj0mFFv1uwRvMfh44IBsF7au7McvfPd8tS3PkZbc6dv7BT5fwi5Ox0lRvBQrxyHKnZ8HvnfmQCXzGBVdZk5FemYEtxfWTakbtVO+0QvILaPwPBHcTkYtTGbFnSPzoWhdgBaCy4XylGxLJqdt3RZE+GzS6dOcipMiJmI9dL5yn+IYUq4Ngmq2jZDcCQ8Xd5wIhPED6SLDShSrLmKs33kn0MWag44pxffEsddT/M1u4j/vBNi3NAVj9iuAl5eHOAEgTfHAOOSwWTK7mxPb6pK4kItKuVRCjUvCsKE8sOZDl6wwboZl+x/PuFYj6lsIcnwsO7b/pxvSzVQvQ7K+7z3abmHQVjeBD6jeyXhAY/+FbqqyZiyhenKS58UfHqrBQ2LnwfXhwPPW6rVO4V8AHfgeF5Oo=
